### ISSUE TITLE
Right-clicking on a Telerik RadTreeNode

### ISSUE THREAD

**Issue by GailBowen** [HtmlUnit/NHtmlUnit#16]
![radtreenode](https://cloud.githubusercontent.com/assets/11610923/6777718/2902b622-d144-11e4-8bce-e66ecf2f3c59.png)

If I try to right-click on a Telerik RadTreeNode using NHtmlUnit, nothing happens. Please help. I can send you an example project if you send me the email to send it to.

I'm right-clicking on 'Amazing Weekend Package' in the attached screenshot. It normally brings up a context menu.

**Comment by asbjornu** [comment]
I would be very surprised if this worked at all. NHtmlUnit's foundation, [HtmlUnit](http://htmlunit.sourceforge.net/) only has basic support for interactive actions like this and since right-clicking on web pages is both exotic and a bad idea altogether, I wouldn't trust NHtmlUnit to make that work in any way. You may have better luck with [PhantomJS](http://phantomjs.org/), but my recommendation would be to don't rely on right-clicks on the web at all.

**Comment by GailBowen** [comment]
Thank you replying so quickly. I've done other right-clicks. If I create a simple <ul>, I can right-click on the li elements and be taken to a new page.
